# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DSIII.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 870)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_birth = QtWidgets.QLabel(self.centralwidget)
        self.label_birth.setGeometry(QtCore.QRect(90, 90, 40, 30))
        self.label_birth.setObjectName("label_birth")
        self.label_level = QtWidgets.QLabel(self.centralwidget)
        self.label_level.setGeometry(QtCore.QRect(90, 130, 40, 30))
        self.label_level.setObjectName("label_level")
        self.label_soulsToNext = QtWidgets.QLabel(self.centralwidget)
        self.label_soulsToNext.setGeometry(QtCore.QRect(90, 170, 130, 30))
        self.label_soulsToNext.setObjectName("label_soulsToNext")
        self.label_soulsSpendSum = QtWidgets.QLabel(self.centralwidget)
        self.label_soulsSpendSum.setGeometry(QtCore.QRect(90, 210, 130, 30))
        self.label_soulsSpendSum.setObjectName("label_soulsSpendSum")
        self.label_Attribute = QtWidgets.QLabel(self.centralwidget)
        self.label_Attribute.setGeometry(QtCore.QRect(140, 340, 70, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_Attribute.setFont(font)
        self.label_Attribute.setStyleSheet("color:red;")
        self.label_Attribute.setObjectName("label_Attribute")
        self.label_vigor = QtWidgets.QLabel(self.centralwidget)
        self.label_vigor.setGeometry(QtCore.QRect(140, 388, 100, 33))
        self.label_vigor.setObjectName("label_vigor")
        self.label_attunement = QtWidgets.QLabel(self.centralwidget)
        self.label_attunement.setGeometry(QtCore.QRect(140, 428, 100, 33))
        self.label_attunement.setObjectName("label_attunement")
        self.label_endurance = QtWidgets.QLabel(self.centralwidget)
        self.label_endurance.setGeometry(QtCore.QRect(140, 468, 100, 33))
        self.label_endurance.setObjectName("label_endurance")
        self.label_vitality = QtWidgets.QLabel(self.centralwidget)
        self.label_vitality.setGeometry(QtCore.QRect(140, 508, 100, 33))
        self.label_vitality.setObjectName("label_vitality")
        self.label_strength = QtWidgets.QLabel(self.centralwidget)
        self.label_strength.setGeometry(QtCore.QRect(140, 548, 100, 33))
        self.label_strength.setObjectName("label_strength")
        self.label_dexterity = QtWidgets.QLabel(self.centralwidget)
        self.label_dexterity.setGeometry(QtCore.QRect(140, 588, 100, 33))
        self.label_dexterity.setObjectName("label_dexterity")
        self.label_intelligence = QtWidgets.QLabel(self.centralwidget)
        self.label_intelligence.setGeometry(QtCore.QRect(140, 628, 100, 33))
        self.label_intelligence.setObjectName("label_intelligence")
        self.label_faith = QtWidgets.QLabel(self.centralwidget)
        self.label_faith.setGeometry(QtCore.QRect(140, 668, 100, 33))
        self.label_faith.setObjectName("label_faith")
        self.label_luck = QtWidgets.QLabel(self.centralwidget)
        self.label_luck.setGeometry(QtCore.QRect(140, 708, 100, 33))
        self.label_luck.setObjectName("label_luck")
        self.text_Level = QtWidgets.QLabel(self.centralwidget)
        self.text_Level.setGeometry(QtCore.QRect(250, 130, 100, 30))
        self.text_Level.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Level.setObjectName("text_Level")
        self.text_soulsToNext = QtWidgets.QLabel(self.centralwidget)
        self.text_soulsToNext.setGeometry(QtCore.QRect(250, 170, 100, 30))
        self.text_soulsToNext.setFrameShape(QtWidgets.QFrame.Box)
        self.text_soulsToNext.setObjectName("text_soulsToNext")
        self.text_soulsSpendSum = QtWidgets.QLabel(self.centralwidget)
        self.text_soulsSpendSum.setGeometry(QtCore.QRect(250, 210, 100, 30))
        self.text_soulsSpendSum.setFrameShape(QtWidgets.QFrame.Box)
        self.text_soulsSpendSum.setObjectName("text_soulsSpendSum")
        self.label_Init = QtWidgets.QLabel(self.centralwidget)
        self.label_Init.setGeometry(QtCore.QRect(270, 340, 30, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_Init.setFont(font)
        self.label_Init.setStyleSheet("color:red;")
        self.label_Init.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Init.setObjectName("label_Init")
        self.label_Current = QtWidgets.QLabel(self.centralwidget)
        self.label_Current.setGeometry(QtCore.QRect(360, 340, 60, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_Current.setFont(font)
        self.label_Current.setStyleSheet("color:red;")
        self.label_Current.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Current.setObjectName("label_Current")
        self.init_vigor = QtWidgets.QLabel(self.centralwidget)
        self.init_vigor.setGeometry(QtCore.QRect(270, 388, 30, 33))
        self.init_vigor.setAlignment(QtCore.Qt.AlignCenter)
        self.init_vigor.setObjectName("init_vigor")
        self.init_attunement = QtWidgets.QLabel(self.centralwidget)
        self.init_attunement.setGeometry(QtCore.QRect(270, 428, 30, 33))
        self.init_attunement.setAlignment(QtCore.Qt.AlignCenter)
        self.init_attunement.setObjectName("init_attunement")
        self.init_endurance = QtWidgets.QLabel(self.centralwidget)
        self.init_endurance.setGeometry(QtCore.QRect(270, 468, 30, 33))
        self.init_endurance.setAlignment(QtCore.Qt.AlignCenter)
        self.init_endurance.setObjectName("init_endurance")
        self.init_vitality = QtWidgets.QLabel(self.centralwidget)
        self.init_vitality.setGeometry(QtCore.QRect(270, 508, 30, 33))
        self.init_vitality.setAlignment(QtCore.Qt.AlignCenter)
        self.init_vitality.setObjectName("init_vitality")
        self.init_strength = QtWidgets.QLabel(self.centralwidget)
        self.init_strength.setGeometry(QtCore.QRect(270, 548, 30, 33))
        self.init_strength.setAlignment(QtCore.Qt.AlignCenter)
        self.init_strength.setObjectName("init_strength")
        self.init_dexterity = QtWidgets.QLabel(self.centralwidget)
        self.init_dexterity.setGeometry(QtCore.QRect(270, 588, 30, 33))
        self.init_dexterity.setAlignment(QtCore.Qt.AlignCenter)
        self.init_dexterity.setObjectName("init_dexterity")
        self.init_intelligence = QtWidgets.QLabel(self.centralwidget)
        self.init_intelligence.setGeometry(QtCore.QRect(270, 628, 30, 33))
        self.init_intelligence.setAlignment(QtCore.Qt.AlignCenter)
        self.init_intelligence.setObjectName("init_intelligence")
        self.init_faith = QtWidgets.QLabel(self.centralwidget)
        self.init_faith.setGeometry(QtCore.QRect(270, 668, 30, 33))
        self.init_faith.setAlignment(QtCore.Qt.AlignCenter)
        self.init_faith.setObjectName("init_faith")
        self.init_luck = QtWidgets.QLabel(self.centralwidget)
        self.init_luck.setGeometry(QtCore.QRect(270, 708, 30, 33))
        self.init_luck.setAlignment(QtCore.Qt.AlignCenter)
        self.init_luck.setObjectName("init_luck")
        self.vigor_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.vigor_sub_button.setGeometry(QtCore.QRect(330, 388, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.vigor_sub_button.setFont(font)
        self.vigor_sub_button.setStyleSheet("text-align:up;")
        self.vigor_sub_button.setObjectName("vigor_sub_button")
        self.vigor_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.vigor_add_button.setGeometry(QtCore.QRect(430, 388, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.vigor_add_button.setFont(font)
        self.vigor_add_button.setObjectName("vigor_add_button")
        self.vigor_text = QtWidgets.QLineEdit(self.centralwidget)
        self.vigor_text.setGeometry(QtCore.QRect(360, 390, 60, 33))
        self.vigor_text.setAlignment(QtCore.Qt.AlignCenter)
        self.vigor_text.setObjectName("vigor_text")
        self.attunement_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.attunement_sub_button.setGeometry(QtCore.QRect(330, 428, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.attunement_sub_button.setFont(font)
        self.attunement_sub_button.setStyleSheet("text-align:up;")
        self.attunement_sub_button.setObjectName("attunement_sub_button")
        self.endurance_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.endurance_sub_button.setGeometry(QtCore.QRect(330, 468, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.endurance_sub_button.setFont(font)
        self.endurance_sub_button.setStyleSheet("text-align:up;")
        self.endurance_sub_button.setObjectName("endurance_sub_button")
        self.vitality_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.vitality_sub_button.setGeometry(QtCore.QRect(330, 508, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.vitality_sub_button.setFont(font)
        self.vitality_sub_button.setStyleSheet("text-align:up;")
        self.vitality_sub_button.setObjectName("vitality_sub_button")
        self.strength_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.strength_sub_button.setGeometry(QtCore.QRect(330, 548, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.strength_sub_button.setFont(font)
        self.strength_sub_button.setStyleSheet("text-align:up;")
        self.strength_sub_button.setObjectName("strength_sub_button")
        self.dexterity_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.dexterity_sub_button.setGeometry(QtCore.QRect(330, 588, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.dexterity_sub_button.setFont(font)
        self.dexterity_sub_button.setStyleSheet("text-align:up;")
        self.dexterity_sub_button.setObjectName("dexterity_sub_button")
        self.intelligence_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.intelligence_sub_button.setGeometry(QtCore.QRect(330, 628, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.intelligence_sub_button.setFont(font)
        self.intelligence_sub_button.setStyleSheet("text-align:up;")
        self.intelligence_sub_button.setObjectName("intelligence_sub_button")
        self.faith_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.faith_sub_button.setGeometry(QtCore.QRect(330, 668, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.faith_sub_button.setFont(font)
        self.faith_sub_button.setStyleSheet("text-align:up;")
        self.faith_sub_button.setObjectName("faith_sub_button")
        self.luck_sub_button = QtWidgets.QPushButton(self.centralwidget)
        self.luck_sub_button.setGeometry(QtCore.QRect(330, 708, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.luck_sub_button.setFont(font)
        self.luck_sub_button.setStyleSheet("text-align:up;")
        self.luck_sub_button.setObjectName("luck_sub_button")
        self.attunement_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.attunement_add_button.setGeometry(QtCore.QRect(430, 428, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.attunement_add_button.setFont(font)
        self.attunement_add_button.setObjectName("attunement_add_button")
        self.endurance_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.endurance_add_button.setGeometry(QtCore.QRect(430, 468, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.endurance_add_button.setFont(font)
        self.endurance_add_button.setObjectName("endurance_add_button")
        self.vitality_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.vitality_add_button.setGeometry(QtCore.QRect(430, 508, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.vitality_add_button.setFont(font)
        self.vitality_add_button.setObjectName("vitality_add_button")
        self.strength_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.strength_add_button.setGeometry(QtCore.QRect(430, 548, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.strength_add_button.setFont(font)
        self.strength_add_button.setObjectName("strength_add_button")
        self.dexterity_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.dexterity_add_button.setGeometry(QtCore.QRect(430, 588, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.dexterity_add_button.setFont(font)
        self.dexterity_add_button.setObjectName("dexterity_add_button")
        self.intelligence_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.intelligence_add_button.setGeometry(QtCore.QRect(430, 628, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.intelligence_add_button.setFont(font)
        self.intelligence_add_button.setObjectName("intelligence_add_button")
        self.faith_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.faith_add_button.setGeometry(QtCore.QRect(430, 668, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.faith_add_button.setFont(font)
        self.faith_add_button.setObjectName("faith_add_button")
        self.luck_add_button = QtWidgets.QPushButton(self.centralwidget)
        self.luck_add_button.setGeometry(QtCore.QRect(430, 708, 20, 36))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(16)
        self.luck_add_button.setFont(font)
        self.luck_add_button.setObjectName("luck_add_button")
        self.attunement_text = QtWidgets.QLineEdit(self.centralwidget)
        self.attunement_text.setGeometry(QtCore.QRect(360, 430, 60, 33))
        self.attunement_text.setAlignment(QtCore.Qt.AlignCenter)
        self.attunement_text.setObjectName("attunement_text")
        self.endurance_text = QtWidgets.QLineEdit(self.centralwidget)
        self.endurance_text.setGeometry(QtCore.QRect(360, 470, 60, 33))
        self.endurance_text.setAlignment(QtCore.Qt.AlignCenter)
        self.endurance_text.setObjectName("endurance_text")
        self.vitality_text = QtWidgets.QLineEdit(self.centralwidget)
        self.vitality_text.setGeometry(QtCore.QRect(360, 510, 60, 33))
        self.vitality_text.setAlignment(QtCore.Qt.AlignCenter)
        self.vitality_text.setObjectName("vitality_text")
        self.strength_text = QtWidgets.QLineEdit(self.centralwidget)
        self.strength_text.setGeometry(QtCore.QRect(360, 550, 60, 33))
        self.strength_text.setAlignment(QtCore.Qt.AlignCenter)
        self.strength_text.setObjectName("strength_text")
        self.dexterity_text = QtWidgets.QLineEdit(self.centralwidget)
        self.dexterity_text.setGeometry(QtCore.QRect(360, 590, 60, 33))
        self.dexterity_text.setAlignment(QtCore.Qt.AlignCenter)
        self.dexterity_text.setObjectName("dexterity_text")
        self.intelligence_text = QtWidgets.QLineEdit(self.centralwidget)
        self.intelligence_text.setGeometry(QtCore.QRect(360, 630, 60, 33))
        self.intelligence_text.setAlignment(QtCore.Qt.AlignCenter)
        self.intelligence_text.setObjectName("intelligence_text")
        self.faith_text = QtWidgets.QLineEdit(self.centralwidget)
        self.faith_text.setGeometry(QtCore.QRect(360, 670, 60, 33))
        self.faith_text.setAlignment(QtCore.Qt.AlignCenter)
        self.faith_text.setObjectName("faith_text")
        self.luck_text = QtWidgets.QLineEdit(self.centralwidget)
        self.luck_text.setGeometry(QtCore.QRect(360, 710, 60, 33))
        self.luck_text.setAlignment(QtCore.Qt.AlignCenter)
        self.luck_text.setObjectName("luck_text")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(140, 90, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_HP = QtWidgets.QLabel(self.centralwidget)
        self.label_HP.setGeometry(QtCore.QRect(400, 90, 60, 30))
        self.label_HP.setObjectName("label_HP")
        self.label_FP = QtWidgets.QLabel(self.centralwidget)
        self.label_FP.setGeometry(QtCore.QRect(400, 130, 60, 30))
        self.label_FP.setObjectName("label_FP")
        self.label_Stamina = QtWidgets.QLabel(self.centralwidget)
        self.label_Stamina.setGeometry(QtCore.QRect(400, 170, 60, 30))
        self.label_Stamina.setObjectName("label_Stamina")
        self.label_Equipment_Load = QtWidgets.QLabel(self.centralwidget)
        self.label_Equipment_Load.setGeometry(QtCore.QRect(640, 90, 120, 30))
        self.label_Equipment_Load.setObjectName("label_Equipment_Load")
        self.label_Poise = QtWidgets.QLabel(self.centralwidget)
        self.label_Poise.setGeometry(QtCore.QRect(400, 210, 60, 30))
        self.label_Poise.setObjectName("label_Poise")
        self.label_Item_Discovery = QtWidgets.QLabel(self.centralwidget)
        self.label_Item_Discovery.setGeometry(QtCore.QRect(640, 130, 120, 30))
        self.label_Item_Discovery.setObjectName("label_Item_Discovery")
        self.label_Attunement_Slots = QtWidgets.QLabel(self.centralwidget)
        self.label_Attunement_Slots.setGeometry(QtCore.QRect(640, 170, 120, 30))
        self.label_Attunement_Slots.setObjectName("label_Attunement_Slots")
        self.label_Physical = QtWidgets.QLabel(self.centralwidget)
        self.label_Physical.setGeometry(QtCore.QRect(600, 278, 70, 30))
        self.label_Physical.setObjectName("label_Physical")
        self.label_Strike = QtWidgets.QLabel(self.centralwidget)
        self.label_Strike.setGeometry(QtCore.QRect(615, 318, 70, 30))
        self.label_Strike.setObjectName("label_Strike")
        self.label_Slash = QtWidgets.QLabel(self.centralwidget)
        self.label_Slash.setGeometry(QtCore.QRect(615, 358, 70, 30))
        self.label_Slash.setObjectName("label_Slash")
        self.label_Thrust = QtWidgets.QLabel(self.centralwidget)
        self.label_Thrust.setGeometry(QtCore.QRect(615, 398, 70, 30))
        self.label_Thrust.setObjectName("label_Thrust")
        self.label_Magic = QtWidgets.QLabel(self.centralwidget)
        self.label_Magic.setGeometry(QtCore.QRect(600, 438, 70, 30))
        self.label_Magic.setObjectName("label_Magic")
        self.label_Lightning = QtWidgets.QLabel(self.centralwidget)
        self.label_Lightning.setGeometry(QtCore.QRect(600, 518, 70, 30))
        self.label_Lightning.setObjectName("label_Lightning")
        self.label_Fire = QtWidgets.QLabel(self.centralwidget)
        self.label_Fire.setGeometry(QtCore.QRect(600, 478, 70, 30))
        self.label_Fire.setObjectName("label_Fire")
        self.label_Dark = QtWidgets.QLabel(self.centralwidget)
        self.label_Dark.setGeometry(QtCore.QRect(600, 558, 70, 30))
        self.label_Dark.setObjectName("label_Dark")
        self.label_Defence = QtWidgets.QLabel(self.centralwidget)
        self.label_Defence.setGeometry(QtCore.QRect(760, 238, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_Defence.setFont(font)
        self.label_Defence.setStyleSheet("color:red;")
        self.label_Defence.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Defence.setObjectName("label_Defence")
        self.label_Bleed = QtWidgets.QLabel(self.centralwidget)
        self.label_Bleed.setGeometry(QtCore.QRect(600, 658, 70, 30))
        self.label_Bleed.setObjectName("label_Bleed")
        self.label_Poison = QtWidgets.QLabel(self.centralwidget)
        self.label_Poison.setGeometry(QtCore.QRect(600, 698, 70, 30))
        self.label_Poison.setObjectName("label_Poison")
        self.label_Frost = QtWidgets.QLabel(self.centralwidget)
        self.label_Frost.setGeometry(QtCore.QRect(600, 738, 70, 30))
        self.label_Frost.setObjectName("label_Frost")
        self.label_Curse = QtWidgets.QLabel(self.centralwidget)
        self.label_Curse.setGeometry(QtCore.QRect(600, 778, 70, 30))
        self.label_Curse.setObjectName("label_Curse")
        self.label_Resistances = QtWidgets.QLabel(self.centralwidget)
        self.label_Resistances.setGeometry(QtCore.QRect(760, 618, 100, 30))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_Resistances.setFont(font)
        self.label_Resistances.setStyleSheet("color:red;")
        self.label_Resistances.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Resistances.setObjectName("label_Resistances")
        self.text_FP = QtWidgets.QLabel(self.centralwidget)
        self.text_FP.setGeometry(QtCore.QRect(490, 130, 100, 30))
        self.text_FP.setFrameShape(QtWidgets.QFrame.Box)
        self.text_FP.setObjectName("text_FP")
        self.text_Stamina = QtWidgets.QLabel(self.centralwidget)
        self.text_Stamina.setGeometry(QtCore.QRect(490, 170, 100, 30))
        self.text_Stamina.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Stamina.setObjectName("text_Stamina")
        self.text_Poise = QtWidgets.QLabel(self.centralwidget)
        self.text_Poise.setGeometry(QtCore.QRect(490, 210, 100, 30))
        self.text_Poise.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Poise.setObjectName("text_Poise")
        self.text_Equipment_Load = QtWidgets.QLabel(self.centralwidget)
        self.text_Equipment_Load.setGeometry(QtCore.QRect(790, 90, 100, 30))
        self.text_Equipment_Load.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Equipment_Load.setObjectName("text_Equipment_Load")
        self.text_Attunement_Slots = QtWidgets.QLabel(self.centralwidget)
        self.text_Attunement_Slots.setGeometry(QtCore.QRect(790, 170, 100, 30))
        self.text_Attunement_Slots.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Attunement_Slots.setObjectName("text_Attunement_Slots")
        self.text_HP = QtWidgets.QLabel(self.centralwidget)
        self.text_HP.setGeometry(QtCore.QRect(490, 90, 100, 30))
        self.text_HP.setFrameShape(QtWidgets.QFrame.Box)
        self.text_HP.setObjectName("text_HP")
        self.text_Item_Discovery = QtWidgets.QLabel(self.centralwidget)
        self.text_Item_Discovery.setGeometry(QtCore.QRect(790, 130, 100, 30))
        self.text_Item_Discovery.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Item_Discovery.setObjectName("text_Item_Discovery")
        self.text_Physical = QtWidgets.QLabel(self.centralwidget)
        self.text_Physical.setGeometry(QtCore.QRect(760, 280, 100, 30))
        self.text_Physical.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Physical.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Physical.setObjectName("text_Physical")
        self.text_Strike = QtWidgets.QLabel(self.centralwidget)
        self.text_Strike.setGeometry(QtCore.QRect(760, 320, 100, 30))
        self.text_Strike.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Strike.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Strike.setObjectName("text_Strike")
        self.text_Slash = QtWidgets.QLabel(self.centralwidget)
        self.text_Slash.setGeometry(QtCore.QRect(760, 360, 100, 30))
        self.text_Slash.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Slash.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Slash.setObjectName("text_Slash")
        self.text_Thrust = QtWidgets.QLabel(self.centralwidget)
        self.text_Thrust.setGeometry(QtCore.QRect(760, 400, 100, 30))
        self.text_Thrust.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Thrust.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Thrust.setObjectName("text_Thrust")
        self.text_Magic = QtWidgets.QLabel(self.centralwidget)
        self.text_Magic.setGeometry(QtCore.QRect(760, 440, 100, 30))
        self.text_Magic.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Magic.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Magic.setObjectName("text_Magic")
        self.text_Fire = QtWidgets.QLabel(self.centralwidget)
        self.text_Fire.setGeometry(QtCore.QRect(760, 480, 100, 30))
        self.text_Fire.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Fire.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Fire.setObjectName("text_Fire")
        self.text_Lightning = QtWidgets.QLabel(self.centralwidget)
        self.text_Lightning.setGeometry(QtCore.QRect(760, 520, 100, 30))
        self.text_Lightning.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Lightning.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Lightning.setObjectName("text_Lightning")
        self.text_Dark = QtWidgets.QLabel(self.centralwidget)
        self.text_Dark.setGeometry(QtCore.QRect(760, 560, 100, 30))
        self.text_Dark.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Dark.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Dark.setObjectName("text_Dark")
        self.text_Bleed = QtWidgets.QLabel(self.centralwidget)
        self.text_Bleed.setGeometry(QtCore.QRect(760, 660, 100, 30))
        self.text_Bleed.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Bleed.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Bleed.setObjectName("text_Bleed")
        self.text_Poison = QtWidgets.QLabel(self.centralwidget)
        self.text_Poison.setGeometry(QtCore.QRect(760, 700, 100, 30))
        self.text_Poison.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Poison.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Poison.setObjectName("text_Poison")
        self.text_Frost = QtWidgets.QLabel(self.centralwidget)
        self.text_Frost.setGeometry(QtCore.QRect(760, 740, 100, 30))
        self.text_Frost.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Frost.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Frost.setObjectName("text_Frost")
        self.text_Curse = QtWidgets.QLabel(self.centralwidget)
        self.text_Curse.setGeometry(QtCore.QRect(760, 780, 100, 30))
        self.text_Curse.setFrameShape(QtWidgets.QFrame.Box)
        self.text_Curse.setAlignment(QtCore.Qt.AlignCenter)
        self.text_Curse.setObjectName("text_Curse")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_birth.setText(_translate("MainWindow", "birth"))
        self.label_level.setText(_translate("MainWindow", "level"))
        self.label_soulsToNext.setText(_translate("MainWindow", "Souls to next level"))
        self.label_soulsSpendSum.setText(_translate("MainWindow", "Souls spend sum"))
        self.label_Attribute.setText(_translate("MainWindow", "Attribute"))
        self.label_vigor.setText(_translate("MainWindow", "Vigor"))
        self.label_attunement.setText(_translate("MainWindow", "Attunement"))
        self.label_endurance.setText(_translate("MainWindow", "Endurance"))
        self.label_vitality.setText(_translate("MainWindow", "Vitality"))
        self.label_strength.setText(_translate("MainWindow", "Strength"))
        self.label_dexterity.setText(_translate("MainWindow", "Dexterity"))
        self.label_intelligence.setText(_translate("MainWindow", "Intelligence"))
        self.label_faith.setText(_translate("MainWindow", "Faith"))
        self.label_luck.setText(_translate("MainWindow", "Luck"))
        self.text_Level.setText(_translate("MainWindow", "0"))
        self.text_soulsToNext.setText(_translate("MainWindow", "0"))
        self.text_soulsSpendSum.setText(_translate("MainWindow", "0"))
        self.label_Init.setText(_translate("MainWindow", "Init"))
        self.label_Current.setText(_translate("MainWindow", "Current"))
        self.init_vigor.setText(_translate("MainWindow", "0"))
        self.init_attunement.setText(_translate("MainWindow", "0"))
        self.init_endurance.setText(_translate("MainWindow", "0"))
        self.init_vitality.setText(_translate("MainWindow", "0"))
        self.init_strength.setText(_translate("MainWindow", "0"))
        self.init_dexterity.setText(_translate("MainWindow", "0"))
        self.init_intelligence.setText(_translate("MainWindow", "0"))
        self.init_faith.setText(_translate("MainWindow", "0"))
        self.init_luck.setText(_translate("MainWindow", "0"))
        self.vigor_sub_button.setText(_translate("MainWindow", "-"))
        self.vigor_add_button.setText(_translate("MainWindow", "+"))
        self.vigor_text.setText(_translate("MainWindow", "0"))
        self.attunement_sub_button.setText(_translate("MainWindow", "-"))
        self.endurance_sub_button.setText(_translate("MainWindow", "-"))
        self.vitality_sub_button.setText(_translate("MainWindow", "-"))
        self.strength_sub_button.setText(_translate("MainWindow", "-"))
        self.dexterity_sub_button.setText(_translate("MainWindow", "-"))
        self.intelligence_sub_button.setText(_translate("MainWindow", "-"))
        self.faith_sub_button.setText(_translate("MainWindow", "-"))
        self.luck_sub_button.setText(_translate("MainWindow", "-"))
        self.attunement_add_button.setText(_translate("MainWindow", "+"))
        self.endurance_add_button.setText(_translate("MainWindow", "+"))
        self.vitality_add_button.setText(_translate("MainWindow", "+"))
        self.strength_add_button.setText(_translate("MainWindow", "+"))
        self.dexterity_add_button.setText(_translate("MainWindow", "+"))
        self.intelligence_add_button.setText(_translate("MainWindow", "+"))
        self.faith_add_button.setText(_translate("MainWindow", "+"))
        self.luck_add_button.setText(_translate("MainWindow", "+"))
        self.attunement_text.setText(_translate("MainWindow", "0"))
        self.endurance_text.setText(_translate("MainWindow", "0"))
        self.vitality_text.setText(_translate("MainWindow", "0"))
        self.strength_text.setText(_translate("MainWindow", "0"))
        self.dexterity_text.setText(_translate("MainWindow", "0"))
        self.intelligence_text.setText(_translate("MainWindow", "0"))
        self.faith_text.setText(_translate("MainWindow", "0"))
        self.luck_text.setText(_translate("MainWindow", "0"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Knight"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Mercenary"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Warrior"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Herald"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Thief"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Assassin"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Sorcerer"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Pyromancer"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Cleric"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Deprived"))
        self.label_HP.setText(_translate("MainWindow", "HP"))
        self.label_FP.setText(_translate("MainWindow", "FP"))
        self.label_Stamina.setText(_translate("MainWindow", "Stamina"))
        self.label_Equipment_Load.setText(_translate("MainWindow", "Equipment Load"))
        self.label_Poise.setText(_translate("MainWindow", "Poise"))
        self.label_Item_Discovery.setText(_translate("MainWindow", "Item Discovery"))
        self.label_Attunement_Slots.setText(_translate("MainWindow", "Attunement Slots"))
        self.label_Physical.setText(_translate("MainWindow", "Physical"))
        self.label_Strike.setText(_translate("MainWindow", "VS Strike"))
        self.label_Slash.setText(_translate("MainWindow", "VS Slash"))
        self.label_Thrust.setText(_translate("MainWindow", "VS Thrust"))
        self.label_Magic.setText(_translate("MainWindow", "Magic"))
        self.label_Lightning.setText(_translate("MainWindow", "Lightning"))
        self.label_Fire.setText(_translate("MainWindow", "Fire"))
        self.label_Dark.setText(_translate("MainWindow", "Dark"))
        self.label_Defence.setText(_translate("MainWindow", "Defence"))
        self.label_Bleed.setText(_translate("MainWindow", "Bleed"))
        self.label_Poison.setText(_translate("MainWindow", "Poison"))
        self.label_Frost.setText(_translate("MainWindow", "Frost"))
        self.label_Curse.setText(_translate("MainWindow", "Curse"))
        self.label_Resistances.setText(_translate("MainWindow", "Resistances"))
        self.text_FP.setText(_translate("MainWindow", "0"))
        self.text_Stamina.setText(_translate("MainWindow", "0"))
        self.text_Poise.setText(_translate("MainWindow", "0"))
        self.text_Equipment_Load.setText(_translate("MainWindow", "0"))
        self.text_Attunement_Slots.setText(_translate("MainWindow", "0"))
        self.text_HP.setText(_translate("MainWindow", "0"))
        self.text_Item_Discovery.setText(_translate("MainWindow", "0"))
        self.text_Physical.setText(_translate("MainWindow", "0"))
        self.text_Strike.setText(_translate("MainWindow", "0"))
        self.text_Slash.setText(_translate("MainWindow", "0"))
        self.text_Thrust.setText(_translate("MainWindow", "0"))
        self.text_Magic.setText(_translate("MainWindow", "0"))
        self.text_Fire.setText(_translate("MainWindow", "0"))
        self.text_Lightning.setText(_translate("MainWindow", "0"))
        self.text_Dark.setText(_translate("MainWindow", "0"))
        self.text_Bleed.setText(_translate("MainWindow", "0"))
        self.text_Poison.setText(_translate("MainWindow", "0"))
        self.text_Frost.setText(_translate("MainWindow", "0"))
        self.text_Curse.setText(_translate("MainWindow", "0"))

